### ISSUE TITLE
Dosn't work behind url-rewrite proxy 

### ISSUE THREAD

**Issue by ieugen** [stonecircle/kue-ui#13]
Hi,

I've tried using it behind a proxy with url rewrite rules and it didn't work. 

Other than that, looks great.

**Comment by arnaudbenard** [comment]
What is the error message that you get?

**Comment by ieugen** [comment]
It fails to load some resources (css and js) because you use absolute paths. There is no way to provide a proxy path when serving url's so the app can render proper url behind proxy. 

I'm using the basic kue ui now so I can't reproduce it right now.

**Comment by JovanAleksic** [comment]
Is there a fix for this, or a workaround?

**Comment by mansona** [comment]
I'm closing this for now because this seems like an issue in the Express side of things. If you could try this again and open an issue on https://github.com/stonecircle/kue-ui-express if you have any issues 👍
