### ISSUE TITLE
No jobs shown after changing KUE db

### ISSUE THREAD

**Issue by cburatto** [stonecircle/kue-ui#22]
By default, KUE uses the first db on Redis. I explicitly changed that by using the  `db : number` option while creating a queue. 

KUE-UI is not showing any jobs now.

Is it possible that this DB change caused KUE-UI to "not find" the jobs? I tried adding a `db : number` to the KUE-UI setup, but that doesn't seem to help.

**Comment by mansona** [comment]
I doubt this would have been an issue on the Kue-Ui side of things, Kue-Ui just connects directly to the Kue API and renders jobs it finds there, it might be an issue with your express implementation.

If you wanted you could try out https://github.com/stonecircle/kue-ui-express and let me know there if you have the same issue that would be great 👍
