### ISSUE TITLE
KUE-UI sends error when shuttingdown and then recreating a kue

### ISSUE THREAD

**Issue by muhammadfaizan** [stonecircle/kue-ui#23]
> TypeError: Cannot read property 'zcard' of null
>     at Queue.card (/Users/dev/Documents/integrity-automation/node_modules/kue/lib/kue.js:502:14)
>     at Queue.inactiveCount (/Users/dev/Documents/integrity-automation/node_modules/kue/lib/kue.js:605:17)
>     at _ (/Users/dev/Documents/integrity-automation/node_modules/kue/lib/http/routes/json.js:305:19)
>     at exports.stats (/Users/dev/Documents/integrity-automation/node_modules/kue/lib/http/routes/json.js:41:3)
>     at Layer.handle [as handle_request](/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/route.js:131:13)
>     at /Users/dev/Documents/integrity-automation/node_modules/kue/lib/http/middleware/provides.js:11:36
>     at Layer.handle [as handle_request](/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/route.js:131:13)
>     at Route.dispatch (/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request](/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/layer.js:95:5)
>     at /Users/dev/Documents/integrity-automation/node_modules/express/lib/router/index.js:277:22
>     at Function.process_params (/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/index.js:330:12)
>     at next (/Users/dev/Documents/integrity-automation/node_modules/express/lib/router/index.js:271:10)
>     at SendStream.error (/Users/dev/Documents/integrity-automation/node_modules/serve-static/index.js:120:7)
>     at emitOne (events.js:77:13)
>     at SendStream.emit (events.js:169:7)
>     at SendStream.error (/Users/dev/Documents/integrity-automation/node_modules/send/index.js:245:17)
>     at SendStream.onStatError (/Users/dev/Documents/integrity-automation/node_modules/send/index.js:356:12)
>     at next (/Users/dev/Documents/integrity-automation/node_modules/send/index.js:630:16)
>     at onstat (/Users/dev/Documents/integrity-automation/node_modules/send/index.js:619:14)
>     at FSReqWrap.oncomplete (fs.js:82:15)

This error appears, when i shutdown que and create a new Kue again,with in the application.
The error appears on /api/stats call from browser on an interval.

**Comment by narainsagar** [comment]
Same here!

**Comment by mmarshak** [comment]
I also get this error upon shutdown when the UI connected, any update on this?

**Comment by mansona** [comment]
This is no longer relevant to this particular repository. If you could try out https://github.com/stonecircle/kue-ui-express and let me know there if you have the same issue that would be great 👍
