### ISSUE TITLE
Is it possible to manually trigger a task from kue-ui?

### ISSUE THREAD

**Issue by coolnalu** [stonecircle/kue-ui#25]
I was able to start kue-ui and spawn a few consumers to process jobs. For verification purposes, I made the server create a new job every few seconds. I could see those job statuses on kue-ui.

My question is: is it possible to manually trigger a job from the UI? If not what's the idiomatic way to trigger a job today?

Thanks!

**Comment by mansona** [comment]
@coolnalu I am pretty sure that you cannot trigger a job from the UI currently, but it doesn't take much to trigger a new job with a curl command. What is your use case? Maybe we could come up with some sort of work around 😄

**Comment by coolnalu** [comment]
@mansona thanks!

one complexity is I've secured my kue-ui with passportjs lol, so curl would require a session token or auth token, so a job name input + create button would be ideal.

the use case is simple: 
- I have kue and kue-ui running as a server, protected by oauth
- I have a bunch of consumer node.js processes listening to the redis server for new job events.

now i want to manually kick off a job (could be a repeat job or could be an one time job), and there doesn't seem a trivial way.
