### ISSUE TITLE
Making kue-ui work with hapi

### ISSUE THREAD

**Issue by snig-b** [stonecircle/kue-ui#26]
I am using **hapi** to create my application. This is created on express, how can I integrate this on my hapi application? I read about proxy hapi routing for this, but not sure about that. Any guidance towards a direction would be highly appreciated.

**Comment by mansona** [comment]
Hey @snig-b, I've just completed a process to separate out the Kue-Ui frontend from the Express implementation on the backend. 

Unfortunately I don't have any experience with hapi routing but you could take a look at the source of https://github.com/stonecircle/kue-ui-express and see what I'm doing there.

It should be self-explanatory (very small integration layer) but please let me know how you get on, and maybe share your experience to help any other hapi users 😂
