### ISSUE TITLE
What does kue-ui do?

### ISSUE THREAD

**Issue by asdf01** [stonecircle/kue-ui#31]
Hey Guys

I was redirected here from the parse-server community.  It sounds like a lot of people are using Kue + Kue-UI to replace parse.com scheduled jobs / cloud jobs.  

With the Kue + Kue-UI setup, can you create new schedules for jobs through Kue-UI's web ui?  Or is Kue-UI just for viewing the state of the Kue based jobs through a web ui?  Looking at the screenshots on [Kue-UI's github](https://github.com/stonecircle/kue-ui), it's not immediately obvious.  

Thanks.

**Comment by rtodea** [comment]
Hi,

To answer your last question, `kue-ui` is for viewing the `kue` based jobs via a web interface.
However, it can change the status of an *already created* job.

Also note that `kue` comes with a minimal web interface where you can replay or delete a job.

On a more general note, `kue` offers a priority job queue: you can enqueue jobs programatically or via a JSON API and write workers that can process the jobs. The lifecycle of the worker must be handled by you.

It does not offer job scheduling like a `crontab`. See projects like [`kue-scheduler`](https://github.com/lykmapipo/kue-scheduler) which add support in this direction.

**Comment by mansona** [comment]
Thanks @rtodea, I think that sums up the project quite well 👍 

The idea of "creating new schedules for jobs" is probably going to be out of scope for quite some time (if not forever) but we have an issue to track the ability to create **single** new job here https://github.com/stonecircle/kue-ui/issues/25

For a deeper understanding of what Kue is I would recommend reading the main Readme here: https://github.com/Automattic/kue
