### ISSUE TITLE
Is there any way to get job using job id?

### ISSUE THREAD

**Issue by rohitprajapati** [stonecircle/kue-ui#33]
Assumption - I know the job id.

If I want to restart my job, I need to scroll down find the required job and then restart it. Sometimes it becomes very difficult. Currently I use the backend api to restart the job. Is there any way to search by job id?

**Comment by mansona** [comment]
@rohitprajapati there is not currently a way to "search" for the job by id but you can just change the URL and go directly to it `https://url.toyour.server/jobs/882882828` where `882882828` is the job Id. 

Does that help?

**Comment by rohitprajapati** [comment]
Thanks mansona for reply, but that give all the json information of the job.

I figured out a way to retstart the job using the api - https://url.my.server/kue/api/inactive/1061314

My question was more related to finding job using search box given job_id.
