### ISSUE TITLE
The build process seems to be wrong?

### ISSUE THREAD

**Issue by changjunhao** [stonecircle/kue-ui#43]
<img width="922" alt="2017-03-03 9 57 17" src="https://cloud.githubusercontent.com/assets/7688639/23553878/a6dfd512-005d-11e7-8f3a-288a9bad7fc2.png">
<img width="471" alt="2017-03-03 10 05 55" src="https://cloud.githubusercontent.com/assets/7688639/23553879/a6e41474-005d-11e7-805f-e43294d67bc8.png">

**Comment by mansona** [comment]
@changjunhao thanks for this, it seems I was using a NPM v4 feature `prepublishOnly` which was essentially getting ignored in NPM v3 during publish. 

v1.1.2 has now been released which fixes this 👍

**Comment by changjunhao** [comment]
When to release v1.1.2, I see now is not good

**Comment by mansona** [comment]
@changjunhao i don't quite know what you're asking... can you try deleting your node_modules and doing `npm install` again?

**Comment by changjunhao** [comment]
Yes,I deleting my node_modules and doing npm install again,but the error remains the same。
PS：npm v4.1.2

**Comment by mansona** [comment]
🙄  it seems like npm have changed another thing about how their internals work! 

I've fixed it now and v1.1.3 should now fix it. Please confirm that it's ok and close the issue 👍

**Comment by changjunhao** [comment]
Thank you very much for actively solving my problem

**Comment by mansona** [comment]
glad it works for you 😄
