### ISSUE TITLE
Question :  Is there a REST API that goes with this?

### ISSUE THREAD

**Issue by sjmcdowall** [stonecircle/kue-ui#51]
On the "standard" Kue dashboard it exposes a restful API .. Does this package also expose a restful API and if so -- where can it be found and how to use it?  I think I see it doing restful type calls to some restful looking api but everything I try returns a "404" type thing and there doesn't appear to be much documentation on this package .. ??

**Comment by mansona** [comment]
Hey @sjmcdowall 👋 

Kue-ui is actually using the API directly from Kue itself. All this is doing is providing a different UI to manage jobs than the "standard" Kue dashboard.

If you want to find out more information about the Kue API I would check out https://github.com/Automattic/kue
